### ISSUE TITLE
Use last example to talk about statement form of arrow functions

### ISSUE THREAD

**Issue by domenic** [tastejs/todomvc-backbone-es6#18]
Arrow functions are introduced in their expression form. The end of the file includes

``` js
$(() => {
    new AppView();
    new Filters();
    Backbone.history.start();
});
```

which would be a good chance to talk about how you can use them for statement forms (including multiple statements).

It _might_ be worth mentioning that the `()` could [go away soon](http://esdiscuss.org/topic/more-concise-arrow-functions). In fact you could even use this to write a sentence or two about es-discuss, features still changing and under flux, community feedback helpful. But that's probably out of scope.

**Comment by addyosmani** [comment]
Updated. If there's anything more to add please do feel free to shout!
