### ISSUE TITLE
More critiques

### ISSUE THREAD

**Issue by domenic** [tastejs/todomvc-backbone-es6#4]
In addition to #3:
- More `const`, less `let`, and never use `var` in ES6.
- No need for parens for single-argument arrow functions.
- Put `'use strict'` at the top (although this will be unnecessary once you move to modules).
- Use `.js` instead of `.es6`.

In addition I just want to strongly second the use of shorthand object literals recommended in #3. After the `var`/`let` usage, that was the biggest thing that stood out to me.

**Comment by addyosmani** [comment]
Thanks @domenic! We really appreciate the feedback and suggestions. We can definitely move to shorthand object literals.

**Comment by domenic** [comment]
I think this is mostly done, I'll (re)open any specific critiques.
