### ISSUE TITLE
Improve code comments

### ISSUE THREAD

**Issue by addyosmani** [tastejs/todomvc-backbone-es6#9]
@passy would you be interested in improving the level of code commenting we have on the project at present? 

I think that we already have reasonable functional comments about what the code is doing, but could document what syntax is newer (ES6) where relevant.

e.g 

```
//
// ES6 module - a unit of source code with optional imports and exports.
//
// ES6 draft: https://people.mozilla.com/~jorendorff/es6-draft.html#sec-14.3
// Examples: http://wiki.ecmascript.org/doku.php?id=harmony:modules
```

**Comment by passy** [comment]
Sure, adding some external resources is a good idea!

**Comment by addyosmani** [comment]
done
